services:
  ktor-app:
    build: .
    ports:
      - "61000:8080"
    environment:
      GUILD: ${GUILD}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      IMPERIAL_WEBSITE_URL: ${IMPERIAL_WEBSITE_URL:-}
    restart: unless-stopped